version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: neo4j/23109900

  python_app:
    build: .
    container_name: python_app_container
    volumes:
      - .:/app
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
