neo4j:
  url: 'neo4j://neo4j_user:7687'
#  url: 'neo4j://neo4j_user:7687'
  user: 'neo4j'
  password: '23109900'

  hist_url: 'neo4j://neo4j_historical:7687' # mail
  hist_password: '23109900'

  # side_url: 'neo4j+s://178ff2cf.databases.neo4j.io:7687' # google

  x2_url: 'neo4j://neo4j_historical:7687' # yandex
  x2_password: '23109900'

  js_url: 'neo4j://localhost:7688'
  js_pass: '23109900'

  # last_url: 'neo4j://127.0.0.1:7688'
  # file: 'data/2021-11-19 Roder связи.xlsx'