neo4j:
  url: 'neo4j://127.0.0.1:7687'
  user: 'neo4j'
  password: '23109900'

  hist_url: 'neo4j+s://99c1a702.databases.neo4j.io:7687'
  hist_password: '231099'

  last_url: 'neo4j://127.0.0.1:7688'
  file: 'data/2021-11-19 Roder связи.xlsx'