neo4j:
  url: 'neo4j://127.0.0.1:7687'
  user: 'neo4j'
  password: '23109900'

  hist_url: 'neo4j+s://99c1a702.databases.neo4j.io:7687' # mail
  hist_password: '231099'

  side_url: 'neo4j+s://178ff2cf.databases.neo4j.io:7687' # google

  x2_url: 'neo4j+s://0fdb78bd.databases.neo4j.io:7687' # yandex
  x2_password: '231099'

  last_url: 'neo4j://127.0.0.1:7688'
  file: 'data/2021-11-19 Roder связи.xlsx'