# Generated by Django 3.2 on 2022-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('projectId', models.CharField(max_length=200)),
                ('modelId', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='URN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('urn', models.CharField(max_length=200)),
                ('userId', models.IntegerField()),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
