# Generated by Django 3.2 on 2022-07-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rule', models.CharField(max_length=9999)),
                ('userId', models.IntegerField()),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
