# Generated by Django 4.1.1 on 2022-10-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task1'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
