# Generated by Django 3.2 on 2022-06-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_urn_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urn',
            name='isActive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
