# Generated by Django 4.1.1 on 2022-10-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task1_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('my_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('progress', models.FloatField()),
                ('parent', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Task1',
        ),
    ]
