# Generated by Django 3.2 on 2022-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220715_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='docsdiv',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='wbs1',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='wbs2',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='wbs3',
        ),
        migrations.AddField(
            model_name='rule',
            name='rule',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
