# Generated by Django 3.2 on 2022-06-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_urn_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urn',
            old_name='name',
            new_name='type',
        ),
    ]
