# Generated by Django 4.1.2 on 2022-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rule_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="isActive",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="userId",
            field=models.IntegerField(blank=True),
        ),
    ]
