# Generated by Django 3.2 on 2022-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_wbs_code_rule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_code', models.CharField(max_length=30)),
                ('docsdiv', models.CharField(max_length=10)),
                ('wbs1', models.CharField(max_length=10)),
                ('wbs2', models.CharField(max_length=100)),
                ('wbs3', models.CharField(max_length=100)),
                ('specs', models.CharField(max_length=200)),
            ],
        ),
    ]
