# Generated by Django 3.2 on 2022-07-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbs',
            name='isActive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbs',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
