# Generated by Django 4.1.3 on 2023-01-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_rule_isactive_alter_rule_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wbs",
            name="specs",
            field=models.JSONField(),
        ),
    ]
