# Generated by Django 4.1.3 on 2023-03-16 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_job_project_modelgroup_jobitem_autodeskextractorrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='myapp.project'),
            preserve_default=False,
        ),
    ]
