# Generated by Django 4.1.2 on 2022-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_task2_duration_alter_task2_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="name",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="rule",
        ),
        migrations.AddField(
            model_name="rule",
            name="fields",
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name="rule",
            name="filters",
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name="rule",
            name="group_by",
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name="rule",
            name="names",
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name="rule",
            name="operations",
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name="rule",
            name="sum_by",
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name="rule",
            name="unique_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
